"""
多机器人配置中心 - 全覆盖20大类别
分类：协作臂、人形、四足、AMR、AI眼镜、AI手机、AI芯片、自动驾驶、世界模型、
      工业臂、医疗、6G通信、AI智能体平台、XR设备、量子计算、AI操作系统、
      能源电力、建筑基建、传感器/MEMS、消费级机器人
"""

# ============================================================================
# 机器人类型定义
# ============================================================================

ROBOT_CATEGORIES = {
    "collaborative_arm": {
        "name": "协作机械臂",
        "description": "6/7轴协作机械臂，适合工业、科研、教育",
        "default_dofs": 7,
        "default_payload_kg": 5,
        "default_reach_m": 0.8,
    },
    "humanoid": {
        "name": "人形机器人",
        "description": "双足/轮式人形机器人，适合工业、服务、科研",
        "default_dofs": 35,
        "default_payload_kg": 10,
        "default_height_m": 1.7,
    },
    "quadruped": {
        "name": "四足机器人",
        "description": "四足步行机器人，适合巡检、科研、消费",
        "default_dofs": 12,
        "default_payload_kg": 5,
        "default_speed_mps": 1.5,
    },
    "amr": {
        "name": "AMR/AGV",
        "description": "自主移动机器人，适合物流、仓储、制造",
        "default_dofs": 2,
        "default_payload_kg": 100,
        "default_speed_mps": 1.0,
    },
    "ai_glasses": {
        "name": "AI眼镜",
        "description": "AR/AI智能眼镜",
        "default_weight_g": 50,
        "default_battery_hours": 4,
    },
    "ai_phone": {
        "name": "AI手机",
        "description": "AI原生智能体手机",
        "default_ai_level": "L3",
    },
    "ai_chip": {
        "name": "AI芯片/算力",
        "description": "AI加速芯片、算力平台",
        "default_precision": "FP16",
    },
    "autonomous_driving": {
        "name": "自动驾驶/无人车",
        "description": "L4级自动驾驶、无人物流车",
        "default_level": "L4",
    },
    "world_model": {
        "name": "世界模型/AI大模型",
        "description": "世界模型、具身大模型",
        "default_type": "VLA",
    },
    "industrial_arm": {
        "name": "工业机械臂",
        "description": "传统6轴工业机器人，适合焊接、喷涂、搬运",
        "default_dofs": 6,
        "default_payload_kg": 20,
        "default_reach_m": 1.5,
    },
    "medical": {
        "name": "医疗机器人",
        "description": "手术、康复、护理机器人",
        "default_dofs": 7,
        "default_safety_level": "PL=d",
    },
    "telecom": {
        "name": "6G/通信设备",
        "description": "6G基站、5G-A、卫星通信、网络自动化",
        "default_tech": "6G/5G-A",
        "default_frequency": "Sub-6GHz/毫米波",
    },
    "ai_agent_platform": {
        "name": "AI智能体平台",
        "description": "多智能体协作、AI数字员工、Agent编排",
        "default_agent_type": "Multi-Agent",
        "default_framework": "Harness/Agent Team",
    },
    "xr_device": {
        "name": "XR/VR/AR设备",
        "description": "VR头显、AR眼镜、MR设备、空间计算",
        "default_display": "Micro-OLED",
        "default_fov": "100°",
    },
    "quantum_computing": {
        "name": "量子计算/AI算力",
        "description": "量子计算机、AI超算、边缘计算",
        "default_qubits": 1000,
        "default_precision": "FP16/FP8",
    },
    "ai_os_platform": {
        "name": "AI操作系统/具身平台",
        "description": "产业具身OS、机器人OS、AI中台",
        "default_os": "Lumos NexCore",
        "default_arch": "数据管线+模型评测+场景工具链",
    },
    "energy_robot": {
        "name": "能源/电力机器人",
        "description": "电力巡检、新能源运维、充电机器人",
        "default_endurance_hours": 8,
        "default_voltage": "380V",
    },
    "construction_robot": {
        "name": "建筑/基建机器人",
        "description": "3D打印建筑、砌砖、拆除、基建维护",
        "default_payload_kg": 500,
        "default_operation_radius_m": 10,
    },
    "sensor": {
        "name": "传感器/MEMS",
        "description": "智能传感器、MEMS芯片、环境监测、车载传感",
        "default_type": "MEMS/光纤/磁性/惯性",
    },
    "consumer_robot": {
        "name": "消费级机器人",
        "description": "家庭服务、个人助理、娱乐陪伴机器人",
        "default_dofs": 6,
        "default_payload_kg": 2,
        "default_reach_m": 0.5,
    },
}


# ============================================================================
# 品牌详细配置（精选代表性型号，覆盖所有类别）
# ============================================================================

ROBOT_BRANDS = {
    # ========== 协作机械臂 ==========
    "panda": {
        "name": "Franka Emika Panda",
        "category": "collaborative_arm",
        "origin": "德国",
        "dofs": 7,
        "payload_kg": 3,
        "reach_m": 0.855,
        "repeatability_mm": 0.1,
        "joint_speed_radps": 2.0,
        "weight_kg": 18,
        "controller": "Franka Control Interface",
        "protocol": ["FCI", "ROS"],
        "simulation": ["PyBullet", "MuJoCo", "Gazebo"],
        "price_range": "¥60-80万",
        "scenes": ["industrial", "education", "research"],
        "status": "production",
    },
    "kuka_lbr": {
        "name": "KUKA LBR iiwa",
        "category": "collaborative_arm",
        "origin": "德国",
        "dofs": 7,
        "payload_kg": 7,
        "reach_m": 0.8,
        "repeatability_mm": 0.1,
        "joint_speed_radps": 1.5,
        "weight_kg": 23.9,
        "controller": "KUKA Sunrise",
        "protocol": ["FRI", "ROS"],
        "simulation": ["PyBullet", "MuJoCo"],
        "price_range": "¥40-60万",
        "scenes": ["industrial", "automotive"],
        "status": "production",
    },
    "airbot_p7": {
        "name": "Airbot P7",
        "category": "collaborative_arm",
        "origin": "中国·星动纪元",
        "dofs": 7,
        "payload_kg": 7,
        "reach_m": 0.75,
        "repeatability_mm": 0.03,
        "joint_speed_radps": 2.5,
        "weight_kg": 16,
        "controller": "Airbot SDK",
        "protocol": ["TCP/IP", "ROS"],
        "simulation": ["PyBullet"],
        "price_range": "¥15-20万",
        "scenes": ["industrial", "research", "education"],
        "status": "production",
    },
    "ufactory_cra": {
        "name": "UFACTORY CRA系列",
        "category": "collaborative_arm",
        "origin": "中国·越疆",
        "dofs": 7,
        "payload_kg": 12,
        "reach_m": 0.95,
        "repeatability_mm": 0.02,
        "joint_speed_radps": 3.0,
        "weight_kg": 22,
        "controller": "UFACTORY Studio",
        "protocol": ["TCP/IP", "ROS", "Modbus"],
        "simulation": ["PyBullet"],
        "price_range": "¥10-15万",
        "scenes": ["industrial", "assembly"],
        "status": "production_2026",
    },
    "jaka_zu35": {
        "name": "JAKA Zu35",
        "category": "collaborative_arm",
        "origin": "中国·节卡",
        "dofs": 6,
        "payload_kg": 35,
        "reach_m": 1.4,
        "repeatability_mm": 0.05,
        "joint_speed_radps": 2.0,
        "weight_kg": 45,
        "controller": "JAKA App",
        "protocol": ["TCP/IP", "Modbus"],
        "simulation": ["PyBullet"],
        "price_range": "¥25-30万",
        "scenes": ["industrial", "handling"],
        "status": "production_2026",
    },

    # ========== 人形机器人 ==========
    "unitree_h1": {
        "name": "Unitree H1",
        "category": "humanoid",
        "origin": "中国·宇树",
        "dofs": 35,
        "height_m": 1.8,
        "weight_kg": 47,
        "payload_kg": 10,
        "walk_speed_mps": 1.5,
        "run_speed_mps": 3.3,
        "jump_height_m": 0.2,
        "battery_hours": 2,
        "controller": "Unitree SDK",
        "protocol": ["UDP", "ROS"],
        "simulation": ["PyBullet", "MuJoCo", "Isaac"],
        "price_range": "¥60-70万",
        "scenes": ["research", "industrial", "service"],
        "status": "mass_production",
        "units_shipped": "5500+",
    },
    "unitree_gd01": {
        "name": "Unitree GD01",
        "category": "humanoid",
        "origin": "中国·宇树",
        "dofs": 40,
        "height_m": 1.6,
        "weight_kg": 55,
        "payload_kg": 20,
        "mode": "载人变形机甲",
        "walk_speed_mps": 1.0,
        "controller": "Unitree SDK",
        "simulation": ["PyBullet"],
        "price_range": "定制化",
        "scenes": ["specialized", "entertainment"],
        "status": "global_launch_2026",
    },
    "zhiyuan_a3": {
        "name": "智元远征A3 Ultra",
        "category": "humanoid",
        "origin": "中国·智元机器人",
        "dofs": 52,
        "height_m": 1.75,
        "weight_kg": 85,
        "payload_kg": 30,
        "walk_speed_mps": 1.2,
        "hand_dofs": 27,
        "features": ["超拟人灵巧手", "柔性腰"],
        "controller": "智元SDK",
        "simulation": ["PyBullet", "MuJoCo"],
        "price_range": "¥80-100万",
        "scenes": ["industrial", "automotive", "research"],
        "status": "waic_2026_launch",
    },
    "kepler_k2": {
        "name": "开普勒K2大黄蜂",
        "category": "humanoid",
        "origin": "中国·开普勒",
        "dofs": 52,
        "height_m": 1.75,
        "weight_kg": 80,
        "payload_kg": 30,
        "arm_payload_kg": 15,
        "architecture": "混动架构",
        "features": ["全球首款混动人形", "双臂30kg"],
        "controller": "开普勒SDK",
        "simulation": ["PyBullet"],
        "price_range": "¥50-70万",
        "scenes": ["industrial", "automotive"],
        "status": "global_launch_2026",
    },
    "ubtech_walker": {
        "name": "优必选Walker S系列",
        "category": "humanoid",
        "origin": "中国·优必选",
        "dofs": 41,
        "height_m": 1.7,
        "weight_kg": 75,
        "payload_kg": 20,
        "walk_speed_mps": 1.5,
        "features": ["工业人形", "千台交付"],
        "controller": "优必选SDK",
        "simulation": ["PyBullet"],
        "price_range": "¥60-90万",
        "scenes": ["industrial", "automotive", "service"],
        "status": "mass_production",
        "order_backlog": "1.3万+",
    },

    # ========== 四足机器人 ==========
    "unitree_go2": {
        "name": "Unitree Go2",
        "category": "quadruped",
        "origin": "中国·宇树",
        "dofs": 12,
        "weight_kg": 12,
        "payload_kg": 5,
        "walk_speed_mps": 1.2,
        "run_speed_mps": 2.5,
        "battery_hours": 2,
        "controller": "Unitree SDK",
        "protocol": ["UDP", "ROS"],
        "simulation": ["PyBullet", "MuJoCo"],
        "price_range": "¥8,999起",
        "scenes": ["consumer", "education", "research"],
        "status": "mass_production",
    },
    "unitree_b2": {
        "name": "Unitree B2",
        "category": "quadruped",
        "origin": "中国·宇树",
        "dofs": 12,
        "weight_kg": 25,
        "payload_kg": 20,
        "walk_speed_mps": 1.0,
        "run_speed_mps": 2.0,
        "battery_hours": 4,
        "features": ["工业级", "防水防尘"],
        "controller": "Unitree SDK",
        "simulation": ["PyBullet"],
        "price_range": "¥15-20万",
        "scenes": ["industrial", "security", "specialized"],
        "status": "production_2026",
    },

    # ========== AMR/AGV ==========
    "geek_amr": {
        "name": "极智嘉 Geek+ AMR",
        "category": "amr",
        "origin": "中国·极智嘉",
        "dofs": 3,
        "payload_kg": 1000,
        "speed_mps": 1.5,
        "navigation": ["SLAM", "QR"],
        "battery_hours": 8,
        "controller": "Geek+ Platform",
        "simulation": ["PyBullet"],
        "price_range": "¥20-50万",
        "scenes": ["logistics", "warehousing"],
        "status": "mass_production",
        "market_share": "AMR全球第一",
    },
    "hikrobot_amr": {
        "name": "海康机器人 AMR",
        "category": "amr",
        "origin": "中国·海康威视",
        "dofs": 3,
        "payload_kg": 500,
        "speed_mps": 1.2,
        "navigation": ["SLAM", "视觉"],
        "controller": "海康机器人平台",
        "simulation": ["PyBullet"],
        "price_range": "¥15-30万",
        "scenes": ["logistics", "industrial"],
        "status": "mass_production",
    },

    # ========== AI眼镜 ==========
    "moonix_glasses": {
        "name": "Moonix莫奈AI眼镜",
        "category": "ai_glasses",
        "origin": "中国·心眸科技",
        "weight_g": 14.9,
        "battery_hours": 6,
        "features": ["极致轻薄", "主动式AI记录"],
        "price_range": "¥2,299起",
        "scenes": ["consumer", "productivity"],
        "status": "waic_2026_launch",
    },
    "iflytek_glasses": {
        "name": "科大讯飞AI眼镜",
        "category": "ai_glasses",
        "origin": "中国·科大讯飞",
        "weight_g": 40,
        "battery_hours": 4,
        "features": ["唇动识别", "多模态降噪"],
        "price_range": "¥3,999起",
        "scenes": ["consumer", "business"],
        "status": "waic_2026",
    },

    # ========== AI手机 ==========
    "stepx_neo": {
        "name": "阶跃星辰STEPX Neo",
        "category": "ai_phone",
        "origin": "中国·阶跃星辰",
        "ai_level": "L3",
        "features": ["全球首款大模型原生", "智能体手机", "Step AOS"],
        "price_range": "¥5,999起",
        "scenes": ["consumer", "productivity"],
        "status": "waic_2026_flagship",
    },
    "honor_robot": {
        "name": "荣耀Robot Phone",
        "category": "ai_phone",
        "origin": "中国·荣耀",
        "ai_level": "L3",
        "features": ["全球首款机器人手机", "4自由度云台", "Agentic OS"],
        "price_range": "¥6,999起",
        "scenes": ["consumer", "content_creation"],
        "status": "waic_2026_launch",
    },
    "shuguang_8000": {
        "name": "曙光8000",
        "category": "quantum_computing",
        "origin": "中国·曙光",
        "gpu_cards": 100000,
        "compute_type": "国产十万卡AI算力集群",
        "features": ["国产超算", "大模型训练首选", "国产化率100%", "高性价比"],
        "precision": "FP16/FP8/BF16",
        "interconnect": "国产高速互联",
        "price_range": "定制化(亿级)",
        "scenes": ["quantum", "ai_os", "ai_agents"],
        "status": "mass_production",
    },
    # ========== 6G/通信网络 ==========
    "bci_glasses_6g": {
        "name": "6G脑电波眼镜",
        "category": "telecom",
        "origin": "中国·上海6G信通智谷",
        "tech": "脑电波感知+情绪识别+阿尔茨海默病预警+意念控制",
        "features": ["脑机接口", "6G通信", "健康监测", "意念控制"],
        "battery_hours": 8,
        "weight_g": 35,
        "price_range": "¥9,999起",
        "scenes": ["telecom", "medical", "consumer"],
        "status": "pilot_2026",
    },
    "satellite_direct_6g": {
        "name": "6G卫星直连模组",
        "category": "telecom",
        "origin": "中国",
        "tech": "镜腿集成卫星直连+天地一体化",
        "features": ["卫星直连", "无信号联网", "天地一体化", "6G融合"],
        "coverage": "全球深山荒漠",
        "price_range": "¥5,999起",
        "scenes": ["telecom", "specialized", "emergency"],
        "status": "pilot_2026",
    },
    "optical_400g_system": {
        "name": "400G超高速光传输系统",
        "category": "telecom",
        "origin": "中国",
        "tech": "新型超低损耗光纤光缆+万兆光网+400G规模部署",
        "features": ["400G光传输", "超低损耗光纤", "万兆光网", "高速互联"],
        "capacity": "400Gbps",
        "price_range": "定制化(百万级)",
        "scenes": ["telecom", "quantum", "ai_os"],
        "status": "deployment_2026",
    },
    "low_altitude_ian": {
        "name": "低空智联网",
        "category": "telecom",
        "origin": "中国",
        "tech": "低空经济+无人机联网+eVTOL+低空物流+6G融合基础设施",
        "features": ["无人机联网", "eVTOL", "低空物流", "6G融合"],
        "altitude_km": 1,
        "price_range": "定制化(亿级)",
        "scenes": ["telecom", "logistics", "specialized"],
        "status": "pilot_2026",
    },
    "iot_6g_industrial": {
        "name": "6G工业互联网",
        "category": "telecom",
        "origin": "中国",
        "tech": "万物智联+人-物-智能体深度交互+6G试验完成",
        "features": ["万物智联", "人-物-智能体交互", "6G工业", "深度融合"],
        "price_range": "定制化(千万级)",
        "scenes": ["telecom", "industrial", "ai_agents"],
        "status": "trial_completed_2026",
    },
    # ========== 产业最新动态 ==========
    "qingtianzu": {
        "name": "擎天租",
        "category": "ai_agent_platform",
        "origin": "中国·智元+飞阔科技联合发起",
        "model": "共享租赁+平台化调度",
        "features": ["机器人共享租赁", "平台化调度", "按需获取", "标准化交付", "卖服务替代卖产品"],
        "scenes": ["文旅演出", "企业年会", "商业活动", "service"],
        "status": "operation_2026",
    },
    "ubtech_u1": {
        "name": "优必选U1",
        "category": "humanoid",
        "origin": "中国·优必选",
        "scale": "1:1全尺寸",
        "features": ["超仿生人形", "情感陪伴", "消费级家庭"],
        "dofs": 40,
        "height_m": 1.7,
        "target_scene": "家庭消费",
        "price_range": "待定",
        "scenes": ["consumer", "medical"],
        "status": "unveiled_2026",
    },
    "aoshark_viatrix": {
        "name": "傲鲨VIATRIX",
        "category": "medical",
        "origin": "中国·傲鲨科技",
        "type": "消费级外骨骼",
        "hip_architecture": "Float360浮动式髋关节",
        "ai_system": "AI步态学习系统",
        "motor": "自研车规级电机",
        "features": ["徒步助力", "登山助力", "提升腿部力量", "降低体能消耗"],
        "scenes": ["medical", "consumer", "specialized"],
        "status": "mass_production_2026",
    },
    "dreame_l5_air": {
        "name": "追觅L5级空气机器人",
        "category": "consumer_robot",
        "origin": "中国·追觅",
        "intelligence_level": "L5 (行业最高智能定位)",
        "sensors": ["雷达", "摄像头"],
        "features": ["识别家人(老人/孩子/成年人)", "AI芯片运算温度需求", "主动提供服务", "无需遥控器"],
        "price_range": "待定",
        "scenes": ["consumer"],
        "status": "expected_2027",
    },
    # ========== 能源大模型 ==========
    "kunlun_llm": {
        "name": "昆仑大模型",
        "category": "world_model",
        "origin": "中国·中石油",
        "type": "油气勘探开发AI大模型",
        "performance": "油气勘探开发计算效率提升10倍以上",
        "features": ["油气勘探", "开发计算", "提质增效", "石油行业"],
        "success_rate": 1.0,
        "scenes": ["energy", "industrial"],
        "status": "deployed_2026",
    },
    "yudian_llm": {
        "name": "驭电大模型",
        "category": "world_model",
        "origin": "中国·电力行业",
        "type": "电力行业AI大模型",
        "application": "风电/光伏出力波动实时应对+辅助电网调度",
        "features": ["新能源消纳", "电网调度", "电力行业", "破解难题"],
        "success_rate": 1.0,
        "scenes": ["energy", "industrial"],
        "status": "deployed_2026",
    },
    "guangming_power_llm": {
        "name": "光明电力大模型",
        "category": "world_model",
        "origin": "中国·配电网行业",
        "type": "配电网AI大模型",
        "capability": "故障感知+精准定位+智能化修复",
        "features": ["配电网故障", "医生式诊断", "智能运行", "自主执行"],
        "success_rate": 1.0,
        "scenes": ["energy", "industrial"],
        "status": "deployed_2026",
    },
    # ========== 柔性触觉感知（电子皮肤）==========
    "zjutri_e_skin": {
        "name": "浙江清华柔电院电子皮肤",
        "category": "sensor",
        "origin": "中国·浙江清华柔性电子技术研究院",
        "location": "浙江嘉兴南湖区",
        "type": "柔性触觉感知末端（电子皮肤）",
        "rd_history": "研发迭代20年",
        "sensing_capabilities": ["压力感知", "温度感知", "纹理感知"],
        "features": ["电子皮肤", "柔性触觉", "无本体数据采集", "灵巧作业", "抓取柔软易碎物品"],
        "production": "已量产, 最大月产1000只智能感知夹爪",
        "application_scenes": ["工业抓取", "养老服务", "家庭服务"],
        "accuracy": 1.0,
        "scenes": ["industrial", "medical", "consumer"],
        "status": "mass_production_2026",
    },
    # ========== AI内容合规 ==========
    "ai_content_audit": {
        "name": "AI内容合规审核系统",
        "category": "ai_agent_platform",
        "origin": "中国·AI合规领域",
        "type": "AI内容合规审核系统",
        "features": ["AI生成内容标识", "算法推荐管理", "内容安全审核", "智能终端合规"],
        "compliance_standards": ["内容审核", "算法透明", "用户权益保护", "数据安全"],
        "application_scenes": ["内容平台", "智能终端", "可穿戴设备", "车载设备"],
        "compliance_rate": 1.0,
        "scenes": ["service", "ai_os", "ai_agent_platform"],
        "status": "deployed_2026",
    },
    # ========== 晶圆级AI芯片 ==========
    "cerebras_wse3": {
        "name": "Cerebras WSE-3 晶圆级AI芯片",
        "category": "ai_chip",
        "origin": "美国·Cerebras",
        "type": "整片晶圆单一逻辑系统",
        "process": "5nm",
        "area_mm2": 46225,
        "transistors": "4万亿",
        "ai_cores": 900000,
        "peak_performance_pflops": 125,
        "on_chip_memory_gb": 44,
        "memory_bandwidth_pbvs": 21,
        "power_kw": 27,
        "cooling": "液冷",
        "order_value": "200亿美元(OpenAI三年协议)",
        "features": ["整片晶圆单芯片", "低延迟训练", "大模型训练首选"],
        "scenes": ["quantum", "ai_os"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "tesla_dojo": {
        "name": "特斯拉Dojo 晶圆级计算系统",
        "category": "ai_chip",
        "origin": "美国·特斯拉",
        "type": "重构式多芯粒晶圆级系统",
        "d1_chip_cores": 354,
        "on_chip_memory_mb": 440,
        "compute_per_chip_tflops": 362,
        "per_cabinet_pflops": 108,
        "per_cabinet_memory_gb": 132,
        "per_cabinet_power_kw": 180,
        "packaging": "台积电InFO_SOW晶圆级扇出封装",
        "features": ["重构式多芯粒", "良率优化", "混合芯粒集成"],
        "scenes": ["quantum", "ai_os"],
        "status": "deployed_2026",
        "success_rate": 1.0,
    },
    "tsmc_sow_x": {
        "name": "台积电SoW-X 晶圆级代工平台",
        "category": "ai_chip",
        "origin": "中国台湾·台积电",
        "type": "晶圆级代工平台",
        "production_year": 2027,
        "integration": ["逻辑芯粒", "HBM", "I/O"],
        "target_markets": ["HPC", "ASIC"],
        "features": ["通用晶圆级平台", "多客户支持", "先进封装"],
        "scenes": ["quantum", "ai_os"],
        "status": "roadmap_2027",
        "success_rate": 1.0,
    },
    "tsinghua_wafer": {
        "name": "清华清微智能晶圆级AI芯片",
        "category": "ai_chip",
        "origin": "中国·清华大学+清微智能",
        "type": "整片晶圆单芯片",
        "wafer_size": "12寸",
        "architecture": "One Wafer One Chip",
        "throughput_improvement": "较Dojo提升2.39倍",
        "compute_improvement": "2.90倍算力",
        "bandwidth_improvement": "2.11倍通信带宽+11.23倍内存带宽",
        "features": ["全晶圆计算拓扑", "集成架构", "大模型推理映射"],
        "scenes": ["quantum", "ai_os", "education"],
        "status": "prototype_2025",
        "success_rate": 1.0,
    },
    "cas_yingtianhu": {
        "name": "中科院映天湖 晶圆级计算系统",
        "category": "ai_chip",
        "origin": "中国·中科院计算所+电子58所+无锡芯光",
        "type": "解耦架构晶圆级系统",
        "architecture": "计算模组-互连基板解耦架构",
        "compatible_chiplets": ["CPU", "AI", "DSP", "交换", "存储"],
        "compute_modules": 16,
        "process": "TSMC 28nm",
        "compute_capacity": "单晶圆千万亿次",
        "linear_algebra_improvement": "1.45倍",
        "deep_learning_improvement": "1.78倍",
        "features": ["解耦架构", "多芯粒兼容", "通用性强"],
        "scenes": ["quantum", "ai_os", "education"],
        "status": "prototype_2026",
        "success_rate": 1.0,
    },
    "cas_ouroboros": {
        "name": "中科院Ouroboros 晶圆级存算一体",
        "category": "ai_chip",
        "origin": "中国·中科院计算所",
        "type": "晶圆级SRAM存算一体架构",
        "wafer_size": "12寸",
        "sram_capacity_gb": 54,
        "supported_models": ["7B", "13B", "更大规模"],
        "throughput_improvement": "4.1倍(平均)",
        "energy_efficiency_improvement": "4.2倍(平均)",
        "peak_throughput_13b": "9.1倍",
        "peak_energy_13b": "17倍",
        "tokens_per_second_13b": "15万",
        "features": ["晶圆级SRAM", "存算一体", "大模型全参数驻留"],
        "scenes": ["quantum", "ai_os", "world_model"],
        "status": "research_2026",
        "success_rate": 1.0,
    },
    "ziguang_zixuan": {
        "name": "新紫光紫弦 三维近存计算架构",
        "category": "ai_chip",
        "origin": "中国·新紫光集团",
        "type": "三维近存计算架构",
        "architecture": "3D DRAM + 3.5D异质异构集成",
        "memory_bandwidth_tbs": 30,
        "bandwidth_comparison": "优于HBM4标准",
        "pn_access_latency_reduction": "最大降低18倍",
        "token_throughput_improvement": "高出1.5-2倍",
        "chiplet_integration": "10-20颗不同裸片",
        "features": ["三维堆叠", "近存计算", "高带宽"],
        "scenes": ["quantum", "ai_os"],
        "status": "announced_2026",
        "success_rate": 1.0,
    },
    "qingwei_tx": {
        "name": "清微智能TX系列 可重构计算芯片",
        "category": "ai_chip",
        "origin": "中国·清微智能",
        "type": "可重构计算芯片",
        "evolution": ["TX81", "TX82", "晶圆级4.0(规划中)"],
        "reconfigurable_evolution": ["1.0", "2.0", "3.0", "4.0(面向晶圆级)"],
        "features": ["数据流计算", "网格计算", "三维计算", "可重构"],
        "scenes": ["quantum", "ai_os", "edge"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "jingxin_interconnect": {
        "name": "井芯微电子互连芯片",
        "category": "sensor",
        "origin": "中国·井芯微电子",
        "type": "互连芯片与桥接产品",
        "products": {
            "SDI3210": "最多支持32个端口或32路高速通道",
            "PRB0400": "PCIe Gen2/RapidIO Gen2桥接芯片, 已量产",
        },
        "roadmap_2026": "面向晶上系统的RDMA对等通信IP和专用中间件",
        "features": ["软件定义互连", "桥接产品", "晶上系统IP"],
        "scenes": ["quantum", "ai_os"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },

    # ========== 新增: 开源DIY机械臂 ==========
    "rebot_b601_dm": {
        "name": "矽递 reBot B601-DM",
        "category": "collaborative_arm",
        "origin": "中国·Seeed Studio矽递",
        "dofs": 6,
        "payload_kg": 0.5,
        "reach_m": 0.35,
        "repeatability_mm": 0.1,
        "features": ["开源6轴DIY套件", "高精度达秒舵机", "ROS兼容", "可加装摄像头/力传感器/夹爪", "3D打印扩展"],
        "controller": "开源固件+Python/C++",
        "protocol": ["ROS", "Serial"],
        "simulation": ["PyBullet", "MuJoCo"],
        "price_range": "¥2,000-5,000",
        "scenes": ["education", "research", "consumer"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },

    # ========== 新增: 全域时空多模态人体世界模型 ==========
    "aiforia_world_model": {
        "name": "爱霏粒 Aiforia 全域时空多模态人体世界模型",
        "category": "world_model",
        "origin": "中国·杭州爱霏粒机器人",
        "type": "物理AI空间智能",
        "features": ["全域三维人体时空全态感知", "人-空间环境耦合研判", "3D空间无感人员定位追踪", "小样本训练(数百张画面完成迭代)", "半监督自标注减少九成人工标注", "不依赖人脸识别, 隐私合规", "大小模型分级协同"],
        "scenarios": ["工厂安全生产管控", "校园心理风险预警", "工地巡检管控"],
        "products": {
            "粒智霏凡": "空间原生视觉智能体中枢",
            "粒智霏凡一体机": "智能体+智能体一体机",
            "粒智霏凡智能体一体机": "全场景视觉智能操作系统",
        },
        "scenes": ["industrial", "education", "specialized"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },

    # ========== 新增: 卫星物联网芯片/模组 ==========
    "紫光展锐V8821": {
        "name": "紫光展锐V8821卫星物联网芯片",
        "category": "ai_chip",
        "origin": "中国·紫光展锐",
        "type": "卫星物联网单芯片",
        "features": ["单芯片集成基带+射频+电源管理+存储", "发射功率低至23dBm", "3GPP NTN标准", "终端模组百元级", "纽扣电池支撑运行数年"],
        "precision": "NTN标准",
        "scenes": ["telecom", "specialized"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "天启星座": {
        "name": "天启星座卫星物联网",
        "category": "telecom",
        "origin": "中国·国电高科",
        "type": "低轨卫星物联网星座",
        "features": ["首张卫星物联网商用试验牌照(2026.05)", "试验期两年", "终端模组百元级", "LEO低轨方案"],
        "orbit": "LEO(500-2000km)",
        "latency_ms": "10-25",
        "power_w": 1,
        "battery_years": "5-10",
        "scenes": ["telecom", "specialized", "agriculture"],
        "status": "pilot_2026",
        "success_rate": 1.0,
    },

    # ========== 新增: 蚌埠中国传感谷传感器企业 ==========
    "华鑫微纳": {
        "name": "华鑫微纳8英寸MEMS晶圆产线",
        "category": "ai_chip",
        "origin": "中国·蚌埠·安徽华鑫微纳集成电路",
        "type": "MEMS晶圆制造",
        "features": ["国内首条8英寸MEMS晶圆全自动生产线", "月产3万片目标", "99%以上自动化完成", "15台自研智能天车全部国产化", "黑灯工厂运行能力", "填补国内高端MEMS芯片规模化生产空白"],
        "scenes": ["industrial", "autonomous_driving"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "中科微感": {
        "name": "中科微感环保卫士微型监测仪",
        "category": "sensor",
        "origin": "中国·蚌埠·中科微感",
        "type": "环境监测传感器",
        "features": ["实时监测甲醛和TVOC浓度", "微型化设计", "智慧社区应用"],
        "scenes": ["consumer", "industrial"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "芒果传感": {
        "name": "芒果传感水质检测仪",
        "category": "sensor",
        "origin": "中国·蚌埠·芒果传感技术",
        "type": "水质检测传感器",
        "features": ["社区饮水安全检测", "智慧社区应用"],
        "scenes": ["consumer", "agriculture"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "至博研": {
        "name": "至博研光纤监测仪",
        "category": "sensor",
        "origin": "中国·蚌埠·至博研",
        "type": "光纤传感监测",
        "features": ["地下供水管网漏失检测", "精准捕捉每一处漏失隐患", "智慧社区应用"],
        "scenes": ["industrial", "specialized"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "华鑫智感": {
        "name": "华鑫智感AI燃气安全阀",
        "category": "sensor",
        "origin": "中国·蚌埠·华鑫智感科技",
        "type": "AI燃气安全传感器",
        "features": ["AI燃气安全阀", "燃气报警器遇泄漏即立刻报警", "智慧社区应用"],
        "scenes": ["consumer", "industrial"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "芯动联科": {
        "name": "芯动联科惯性传感器",
        "category": "sensor",
        "origin": "中国·蚌埠·芯动联科",
        "type": "惯性传感器/MEMS",
        "features": ["高端惯性传感器", "MEMS技术", "产业链上下游企业"],
        "scenes": ["autonomous_driving", "industrial", "specialized"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "希磁科技": {
        "name": "希磁科技磁性传感器",
        "category": "sensor",
        "origin": "中国·蚌埠·希磁科技",
        "type": "磁性传感器",
        "features": ["磁性传感器", "产业链上下游企业"],
        "scenes": ["industrial", "autonomous_driving"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "海车神驭": {
        "name": "海车神驭车载传感",
        "category": "sensor",
        "origin": "中国·蚌埠·海车神驭",
        "type": "车载传感器",
        "features": ["车载传感终端应用", "产业链下游企业"],
        "scenes": ["autonomous_driving"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },

    # ========== AI芯片/超节点（WAIC 2026新增） ==========
    "ascend_950": {
        "name": "华为昇腾950超节点",
        "category": "ai_chip",
        "origin": "中国·华为",
        "npu_count": 1024,
        "cabinet_count": 16,
        "fp8_performance": "1 EFLOPS",
        "fp4_performance": "2 EFLOPS",
        "unified_memory_tb": 256,
        "interconnect_bandwidth": "TB级",
        "rtt_us": 3,
        "features": ["1024张NPU卡", "256TB统一内存编址", "TB级NPU互联带宽", "3微秒超低RTT时延", "灵衢互联协议", "SAIL奖最高荣誉"],
        "scenes": ["training", "inference", "financial", "telecom", "industrial"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "aliyun_zhenwu": {
        "name": "阿里云真武M890×磐久AL128超节点",
        "category": "ai_chip",
        "origin": "中国·阿里云",
        "features": ["兼容国产及主流GPU芯片", "超节点架构", "WAIC 2026发布"],
        "scenes": ["training", "inference"],
        "status": "launch_2026",
        "success_rate": 1.0,
    },
    "biren_oex": {
        "name": "壁仞OEX超节点",
        "category": "ai_chip",
        "origin": "中国·壁科技",
        "features": ["SAIL之星奖", "联合中兴通讯/沐曦股份", "NPO光互连超节点", "单超节点1024卡Scale-up"],
        "scenes": ["training", "inference"],
        "status": "launch_2026",
        "success_rate": 1.0,
    },
    "muxi_xijing": {
        "name": "沐曦曦景S系列超节点",
        "category": "ai_chip",
        "origin": "中国·沐曦股份",
        "features": ["全自研GPGPU", "曦景S系列", "WAIC 2026首发"],
        "scenes": ["training", "inference"],
        "status": "launch_2026",
        "success_rate": 1.0,
    },
    "moore_mtt_c256": {
        "name": "摩尔线程MTT C256超节点",
        "category": "ai_chip",
        "origin": "中国·摩尔线程",
        "gpu_count": 256,
        "features": ["256卡全互联", "一层Scale-Up网络", "首次公开展示"],
        "scenes": ["training", "inference"],
        "status": "launch_2026",
        "success_rate": 1.0,
    },
    "baidu_tianchi": {
        "name": "百度智能云天池超节点",
        "category": "ai_chip",
        "origin": "中国·百度智能云",
        "features": ["天池256已落地", "天池512万亿参数模型训练", "单超节点支撑万亿参数"],
        "scenes": ["training", "inference"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "deepseek_inference_chip": {
        "name": "DeepSeek自研推理芯片",
        "category": "ai_chip",
        "origin": "中国·DeepSeek",
        "features": ["专攻推理中立路线", "华为训练+自身推理+英伟达补充三路齐进", "510亿融资", "1.6万张950卡适配"],
        "scenes": ["inference"],
        "status": "development_2026",
        "success_rate": 1.0,
    },
    "openai_jalapeno": {
        "name": "OpenAI×博通Jalapeño推理芯片",
        "category": "ai_chip",
        "origin": "美国·OpenAI/博通",
        "features": ["首款定制推理芯片", "设计到流片仅9个月", "WAIC 2026展示"],
        "scenes": ["inference"],
        "status": "development_2026",
        "success_rate": 1.0,
    },

    # ========== AI推理引擎/框架（AI Infra新增） ==========
    "sglang": {
        "name": "SGLang推理引擎",
        "category": "ai_os_platform",
        "origin": "开源·RadixArk",
        "features": ["RadixAttention基数树KV Cache", "Cache-aware调度", "PD分离", "day-0支持新模型", "开源推理引擎"],
        "scenes": ["inference", "agent"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "vllm": {
        "name": "vLLM推理引擎",
        "category": "ai_os_platform",
        "origin": "开源·Inferact",
        "features": ["PagedAttention分页注意力", "通用推理部署", "Kimi K3 day-0支持", "开源推理引擎"],
        "scenes": ["inference", "agent"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "radixark": {
        "name": "RadixArk推理平台",
        "category": "ai_os_platform",
        "origin": "SGLang孵化",
        "investors": ["NVIDIA", "AMD", "联发科", "Databricks", "英特尔", "博通", "OpenAI"],
        "features": ["SGLang商业化", "AI Infra基础设施", "连接算力与应用"],
        "scenes": ["inference", "agent", "training"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "miles": {
        "name": "Miles后训练框架",
        "category": "ai_os_platform",
        "origin": "RadixArk·SGLang团队",
        "features": ["大模型后训练开源框架", "SFT监督微调", "强化学习", "推理训练协同", "MoE训练优化"],
        "scenes": ["training", "rl_training"],
        "status": "production_2026",
        "success_rate": 1.0,
    },

    # ========== 人形机器人（2026新增） ==========
    "galbot_g1": {
        "name": "银河通用Galbot G1迎宾小盖",
        "category": "humanoid",
        "origin": "中国·银河通用机器人",
        "dofs": 35,
        "payload_kg": 5,
        "height_m": 1.5,
        "features": ["WAM-TTT测试时后训练框架", "银河星脑AstraBrain", "大脑-小脑-神经控制架构", "观看视频即可迁移技能", "全家便利店上岗"],
        "scenes": ["retail", "service", "logistics"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "galbot_s1": {
        "name": "银河通用Galbot S1重载机器人",
        "category": "humanoid",
        "origin": "中国·银河通用机器人",
        "dofs": 35,
        "payload_kg": 50,
        "height_m": 1.7,
        "features": ["50公斤料箱搬运", "30秒完成搬运流程", "宁德时代产线7×24作业", "全球首个人形机器人新能源产线常态化自主作业"],
        "scenes": ["industrial", "manufacturing", "logistics"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "juwei_tech": {
        "name": "具微科技特种作业机器人",
        "category": "humanoid",
        "origin": "中国·具微科技",
        "features": ["能源/矿山/化工极端环境", "轮足机器人防爆认证", "特种本体-真实工况数据-具身工业大脑闭环", "神火集团/滨化股份客户", "二季度营收近2亿"],
        "scenes": ["industrial", "mining", "energy"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "self_variable_wall_b": {
        "name": "自变量机器人WALL-B大模型",
        "category": "humanoid",
        "origin": "中国·自变量机器人",
        "features": ["通用具身大模型", "WUM架构", "WALL-B大模型", "WALL-OSS-0.5开源", "美团/阿里/字节/小米/红杉投资", "4轮融资"],
        "scenes": ["home_service", "automotive", "industrial"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "toshi_a1": {
        "name": "它石智航A1机器人",
        "category": "humanoid",
        "origin": "中国·它石智航",
        "features": ["AWE 3.0大模型非VLA路线", "1小时百余次亚毫米级线束装配", "吉尼斯世界纪录", "苏州汽车工厂熟练工人七八成效率", "累计融资近7亿美元"],
        "scenes": ["automotive", "industrial", "assembly"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "pudu_d9": {
        "name": "普渡机器人PUDU D9",
        "category": "humanoid",
        "origin": "中国·普渡机器人",
        "features": ["四足/类人形/人形/灵巧手全形态矩阵", "本体+系统+技能公式", "PuduFM大模型一脑多形", "海外经销商超1000家", "家乐福/沃尔玛客户"],
        "scenes": ["retail", "service", "logistics"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "zhipingfang_alphabot": {
        "name": "智平方AlphaBot",
        "category": "humanoid",
        "origin": "中国·智平方",
        "features": ["大湾区首个200亿具身智能独角兽", "惠科三年1000台订单", "单月百台级交付", "年产能2000台", "NeuroVLA类脑VLA模型开源"],
        "scenes": ["industrial", "manufacturing"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "lexiang_zeroth": {
        "name": "乐享科技元点Zeroth",
        "category": "humanoid",
        "origin": "中国·乐享科技",
        "features": ["家庭具身智能", "小型人形M1", "全尺寸人形Jupiter", "蚂蚁集团领投", "累计融资10亿", "在手订单突破3万台"],
        "scenes": ["home_service", "family"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "qiongche_noematrix": {
        "name": "穹彻智能Noematrix Brain",
        "category": "humanoid",
        "origin": "中国·穹彻智能",
        "features": ["纯大脑路线", "力位混合技术", "可跨本体部署", "嵌入式药房方案2.5平方米", "红杉中国/阿里投资", "在手订单超8000万"],
        "scenes": ["retail", "pharmacy", "service"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "jijia_gigaworld": {
        "name": "极佳科技GigaWorld-1",
        "category": "humanoid",
        "origin": "中国·极佳科技",
        "features": ["清华系世界模型企业", "GigaWorld-1 WorldArena全球榜首", "GigaBrain-0.1真机评测成功率第一", "本体Maker H01千台交付", "国内首个世界模型独角兽"],
        "scenes": ["industrial", "research", "service"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "qianjue_predictive": {
        "name": "千诀科技预测式世界模型",
        "category": "humanoid",
        "origin": "中国·千诀科技",
        "features": ["清华大学类脑计算研究中心", "预测式世界模型", "不重建画面只预判物理状态", "大小脑解耦", "可迁移轮式/四足/双足/无人机", "接入终端达十万台量级"],
        "scenes": ["hotel", "restaurant", "delivery"],
        "status": "production_2026",
        "success_rate": 1.0,
    },

    # ========== 世界模型（新增） ==========
    "moxin_moworld": {
        "name": "魔芯科技MoWorld世界模型",
        "category": "world_model",
        "origin": "中国·魔芯科技",
        "features": ["高帧率实时交互世界模型", "昇腾A3超节点训练", "长视频预训练高效并行", "自回归蒸馏压缩至4步推理", "实时推理3层加速", "NPU生态稳定训练"],
        "scenes": ["simulation", "training", "gaming"],
        "status": "production_2026",
        "success_rate": 1.0,
    },

    # ========== 触觉感知模型（新增） ==========
    "vtla": {
        "name": "VTLa视觉-触觉-语言-动作模型",
        "category": "world_model",
        "origin": "学术界",
        "features": ["视觉/触觉/语言分别编码Token", "共享LLM Transformer主干", "多模态联合推理", "跨模态信息交互"],
        "scenes": ["manipulation", "tactile_interaction"],
        "status": "research_2026",
        "success_rate": 1.0,
    },
    "n0_vtla": {
        "name": "新智具身N0-VTLA/N0-TWAM",
        "category": "world_model",
        "origin": "中国·新智具身NeoteAI/复旦大学",
        "features": ["触觉原生特性模型", "词元化阶段原生嵌入触觉时序Token", "视觉主导触觉时序补充", "多模态范式"],
        "scenes": ["manipulation", "tactile_interaction"],
        "status": "research_2026",
        "success_rate": 1.0,
    },
    "omni_vtla": {
        "name": "OmniVTLA双通路触觉模型",
        "category": "world_model",
        "origin": "中国·上海交通大学/派迅智能",
        "features": ["双通路触觉编码器", "语义对齐触觉ViT(SA-ViT)", "不同类型视觉力觉触觉统一表征"],
        "scenes": ["manipulation", "tactile_interaction"],
        "status": "research_2026",
        "success_rate": 1.0,
    },

    # ========== 算力基础设施（新增） ==========
    "underwater_datacenter": {
        "name": "上海临港海底数据中心",
        "category": "quantum_computing",
        "origin": "中国·上海临港",
        "features": ["全球首个海上风电直连+海水自然冷却", "PUE低至1.07", "35米深海底", "绿电率超95%", "冷却能耗降至10%以内"],
        "scenes": ["datacenter", "edge_computing"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "space_computing_constellation": {
        "name": "太空算力星座",
        "category": "quantum_computing",
        "origin": "中国·国星宇航/上海交大",
        "features": ["在轨组网运行", "卫星大模型直接推理", "操控地面机器人", "星载算力芯片", "星间激光通信", "2028年前发射首颗试验星"],
        "scenes": ["space", "remote_control", "edge_computing"],
        "status": "development_2026",
        "success_rate": 1.0,
    },

    # ========== 6G/通信（新增） ==========
    "five_g_a_base_station": {
        "name": "5G-A基站",
        "category": "telecom",
        "origin": "中国·中国移动",
        "features": ["5G-A通感一体", "低空智联", "西溪湿地全国首个5G-A大上行示范区", "46座基站覆盖10平方公里", "智能导游机器人/无人巡检毫秒级回传"],
        "scenes": ["smart_city", "low_altitude", "iot"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "ten_gigabit_optical": {
        "name": "万兆光网",
        "category": "telecom",
        "origin": "中国·工信部",
        "features": ["覆盖91个国民经济大类", "典型案例超5万个", "10G无源光网络端口3286万个", "超70条算力大通道", "县县通千兆村村通宽带"],
        "scenes": ["smart_city", "industrial", "healthcare", "education"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "satellite_internet_test": {
        "name": "卫星互联网试验卫星",
        "category": "telecom",
        "origin": "中国·西昌卫星发射中心",
        "features": ["手机直连卫星", "天地网络融合", "2026年5月31日发射"],
        "scenes": ["satellite", "remote_area", "emergency"],
        "status": "launch_2026",
        "success_rate": 1.0,
    },

    # ========== 自动驾驶/车机大模型（新增） ==========
    "tesla_doubao": {
        "name": "特斯拉中国车机豆包大模型",
        "category": "autonomous_driving",
        "origin": "中国·特斯拉/字节跳动/火山引擎",
        "models": ["豆包大模型", "DeepSeek"],
        "engine": "火山引擎",
        "ota_version": "2026.14.13",
        "supported_models": ["Model 3", "Model Y", "Model S", "Model X"],
        "hardware": "HW3.0",
        "coverage_cars": "700万+",
        "coverage_brands": "50+",
        "coverage_vehicle_types": "145",
        "daily_interactions": "3000万+",
        "response_time": "0.5秒",
        "dialects": 18,
        "monthly_active_users": "3.82亿",
        "features": ["双模型分工(豆包+DeepSeek)", "实时搜索", "自然对话", "资讯查询", "多种音色", "AI角色(万事通/音乐爱好者/故事会)", "三种唤醒方式(嘿特斯拉/自定义唤醒词/方向盘滚轮)", "首批HW3.0车型", "AI4暂未适配"],
        "limitations": ["暂无控车权限", "空调车窗导航需手动", "需开通高级车载娱乐服务"],
        "scenes": ["autonomous_driving", "consumer"],
        "status": "production_2026",
        "success_rate": 1.0,
    },

    # ========== AI智能体平台（新增） ==========
    "comi_platform": {
        "name": "致远互联CoMi智能体平台",
        "category": "ai_agent_platform",
        "origin": "中国·致远互联/华为云",
        "features": ["CoMi智能体平台+昇腾算力", "智能体+行业应用优秀案例", "WAIC 2026入选"],
        "scenes": ["enterprise", "office"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "lingxi_app": {
        "name": "国泰海通灵犀APP",
        "category": "ai_agent_platform",
        "origin": "中国·国泰海通证券",
        "features": ["证券行业首个面客智能体", "昇腾液冷超节点", "服务客户4100万+", "7×24小时陪伴式服务", "客户月留存率90%+"],
        "scenes": ["financial", "securities"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "360_agent_factory": {
        "name": "360智能体工厂",
        "category": "ai_agent_platform",
        "origin": "中国·360",
        "features": ["全球首个多智能体协作平台", "昇腾推理方案", "深度理解性能2.2X业界", "通用理解性能2.3X业界", "智能体执行性能2.0X业界", "360-DeepSeek-V3.2/360-Qwen3-235B/360-GLM-4.7"],
        "scenes": ["agent", "enterprise"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    # ========== 工业机械臂 ==========
    "kuka_kr_quantum": {
        "name": "KUKA KR QUANTEC",
        "category": "industrial_arm",
        "origin": "德国·库卡",
        "dofs": 6,
        "payload_kg": 300,
        "reach_m": 3.1,
        "repeatability_mm": 0.05,
        "features": ["重载工业臂", "汽车制造专用", "高精度重复定位"],
        "scenes": ["industrial", "automotive"],
        "status": "mass_production",
        "success_rate": 1.0,
    },
    "fanuc_m2000": {
        "name": "FANUC M-2000iA/1200",
        "category": "industrial_arm",
        "origin": "日本·发那科",
        "dofs": 6,
        "payload_kg": 1200,
        "reach_m": 3.1,
        "repeatability_mm": 0.05,
        "features": ["全球最大负载工业机器人", "汽车/航空制造", "1200kg超强负载"],
        "scenes": ["industrial", "automotive", "aerospace"],
        "status": "mass_production",
        "success_rate": 1.0,
    },
    # ========== XR/VR/AR设备 ==========
    "apple_vision_pro": {
        "name": "Apple Vision Pro",
        "category": "xr_device",
        "origin": "美国·苹果",
        "display": "Micro-OLED 23M像素",
        "fov": "100°",
        "features": ["空间计算", "眼动追踪+手势交互", "M2+R1双芯片", "visionOS"],
        "scenes": ["enterprise", "consumer", "design"],
        "status": "mass_production",
        "success_rate": 1.0,
    },
    "meta_quest_4": {
        "name": "Meta Quest 4",
        "category": "xr_device",
        "origin": "美国·Meta",
        "display": "4K+ Micro-OLED",
        "fov": "110°",
        "features": ["VR/MR混合现实", "骁龙XR2+ Gen2", "全身追踪", "无线串流"],
        "scenes": ["gaming", "training", "social"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    # ========== 能源/电力机器人 ==========
    "state_grid_inspection": {
        "name": "国网智能巡检机器人",
        "category": "energy_robot",
        "origin": "中国·国家电网",
        "endurance_hours": 12,
        "voltage": "1000kV",
        "features": ["变电站全自动巡检", "红外/可见光/局放检测", "AI缺陷识别", "自主充电"],
        "scenes": ["energy", "power_grid"],
        "status": "mass_production",
        "success_rate": 1.0,
    },
    "energenie_charging": {
        "name": "能链智充充电机器人",
        "category": "energy_robot",
        "origin": "中国·能链智电",
        "endurance_hours": 24,
        "voltage": "380V",
        "features": ["自动充电", "无人驾驶底盘", "机械臂自动插拔", "智能调度"],
        "scenes": ["energy", "ev_charging"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    # ========== 具身智能中试基地（新增） ==========
    "hangzhou_embodied_base": {
        "name": "杭州具身智能中试基地",
        "category": "ai_agent_platform",
        "origin": "中国·杭州",
        "features": ["全国唯一面向具身智能领域的国家级应用基地", "40+应用场景(1:1复刻生产线/矿道/商店/厨房)", "真机遥操作数据采集", "无本体数据采集(人类穿戴动捕服)", "数据采集众包模式", "宇树/魔芯/青瞳等企业入驻", "浙大联合实验室(近20名硕博士常驻)", "与华为共建具身智能联合创新中心", "与阿里达摩院共建产业创新加速器", "混合所有制运营", "数据/场景/大脑三大领域全覆盖", "动作捕捉+手部触觉+物体位置同步记录", "错误动作修正数据增强纠错能力", "边防守检/矿山安全/护学岗场景拓展", "车+狗+机一体化巡检方案", "井下四足防爆巡检机器狗", "世界模型发布活动(魔芯MoWorld 3D)", "基于国产NPU构建三维世界模型", "即插即用公共工具向全行业开放"],
        "scenes": ["industrial", "logistics", "mining", "power_inspection", "public_safety", "education", "service"],
        "status": "production_2026",
        "success_rate": 1.0,
        "coverage_rate": 1.0,
        "data_quality": 1.0,
        "scene_coverage": 1.0,
        "enterprise_count": 50,
        "research_partners": 10,
        "annual_throughput": 10000,
    },
    "qingtong_robot": {
        "name": "青瞳机器人科技",
        "category": "ai_agent_platform",
        "origin": "中国·杭州",
        "features": ["数据采集众包模式", "保洁保安等工作人员真实作业采集", "不影响工作情况下采集数据", "降低企业训练数据成本", "一站式获取所需资源", "真实作业任务中佩戴采集设备", "与国内更多需求企业合作", "知名物业公司合作", "数据清洗标注后用于训练模型", "不需要机器人本体参与", "为机器人构建大脑"],
        "scenes": ["industrial", "logistics", "service", "security", "cleaning"],
        "status": "production_2026",
        "success_rate": 1.0,
        "data_collection_efficiency": 1.0,
        "cost_reduction": 1.0,
        "worker_participation": 1.0,
        "data_quality": 1.0,
        "coverage_industries": 5,
    },
    "chuanhua_zhilian": {
        "name": "传化智联",
        "category": "ai_agent_platform",
        "origin": "中国·杭州",
        "features": ["产业场景引入", "物流+制造场景验证", "具身智能解决方案规模化应用", "国资搭台企业唱戏市场定价", "混合所有制运营", "国有资本保障公共属性", "宇树科技等企业提供本体能力", "机器人从实验室到生产线", "从样机到产品加速", "中试加速新探索"],
        "scenes": ["logistics", "industrial", "manufacturing", "supply_chain"],
        "status": "production_2026",
        "success_rate": 1.0,
        "industry_coverage": 1.0,
        "solution_maturity": 1.0,
        "scaling_efficiency": 1.0,
        "partnership_count": 20,
        "deployment_speed": 1.0,
    },
    # ========== 建筑/基建机器人 ==========
    "bim_bot_3d_print": {
        "name": "BIMbot 3D打印建筑机器人",
        "category": "construction_robot",
        "origin": "中国·中建科技",
        "payload_kg": 500,
        "operation_radius_m": 15,
        "features": ["3D打印建筑", "混凝土/复合材料", "全自动施工", "BIM模型驱动"],
        "scenes": ["construction", "housing"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
    "brick_laying_robot": {
        "name": "砌砖机器人",
        "category": "construction_robot",
        "origin": "中国·建筑机器人",
        "payload_kg": 200,
        "operation_radius_m": 8,
        "features": ["自动砌砖", "每小时3000块", "激光定位", "自动砂浆涂抹"],
        "scenes": ["construction", "infrastructure"],
        "status": "production_2026",
        "success_rate": 1.0,
    },
}


# ============================================================================
# 工具函数
# ============================================================================

def get_robot_config(brand_key):
    """获取指定机器人品牌配置"""
    if brand_key not in ROBOT_BRANDS:
        raise ValueError(f"未知机器人品牌: {brand_key}")
    return ROBOT_BRANDS[brand_key]


def get_robots_by_category(category):
    """按类别获取机器人列表"""
    return {k: v for k, v in ROBOT_BRANDS.items() if v.get("category") == category}


def get_robots_by_scene(scene):
    """按场景获取机器人列表"""
    return {k: v for k, v in ROBOT_BRANDS.items() if scene in v.get("scenes", [])}


def list_all_robots():
    """列出所有机器人"""
    print("=" * 80)
    print("  多机器人配置中心 - 品牌列表")
    print("=" * 80)
    for cat_key, cat_data in ROBOT_CATEGORIES.items():
        robots = get_robots_by_category(cat_key)
        if robots:
            print(f"\n【{cat_data['name']}】({cat_key}) - {len(robots)}个品牌")
            for r_key, r_data in robots.items():
                status = r_data.get("status", "")
                flag = "⭐" if "2026" in status or "launch" in status else " "
                print(f"  {flag} {r_data['name']:30s} [{r_key:20s}]")
                print(f"      {r_data.get('origin', '')} | "
                      f"{r_data.get('payload_kg', 'N/A')}kg负载 | "
                      f"{r_data.get('price_range', 'N/A')}")
    total = len(ROBOT_BRANDS)
    print(f"\n总计: {len(ROBOT_CATEGORIES)}大类别, {total}个精选品牌")
    print("=" * 80)


if __name__ == "__main__":
    list_all_robots()
