"""
多机器人配置中心 - 全覆盖135个品牌
分类：协作臂、人形、四足、AMR、AI眼镜、AI手机、AI芯片、自动驾驶、世界模型
"""

# ============================================================================
# 机器人类型定义
# ============================================================================

ROBOT_CATEGORIES = {
    "collaborative_arm": {
        "name": "协作机械臂",
        "description": "6/7轴协作机械臂，适合工业、科研、教育",
        "default_dofs": 7,
        "default_payload_kg": 5,
        "default_reach_m": 0.8,
    },
    "humanoid": {
        "name": "人形机器人",
        "description": "双足/轮式人形机器人，适合工业、服务、科研",
        "default_dofs": 35,
        "default_payload_kg": 10,
        "default_height_m": 1.7,
    },
    "quadruped": {
        "name": "四足机器人",
        "description": "四足步行机器人，适合巡检、科研、消费",
        "default_dofs": 12,
        "default_payload_kg": 5,
        "default_speed_mps": 1.5,
    },
    "amr": {
        "name": "AMR/AGV",
        "description": "自主移动机器人，适合物流、仓储、制造",
        "default_dofs": 2,
        "default_payload_kg": 100,
        "default_speed_mps": 1.0,
    },
    "ai_glasses": {
        "name": "AI眼镜",
        "description": "AR/AI智能眼镜",
        "default_weight_g": 50,
        "default_battery_hours": 4,
    },
    "ai_phone": {
        "name": "AI手机",
        "description": "AI原生智能体手机",
        "default_ai_level": "L3",
    },
    "ai_chip": {
        "name": "AI芯片/算力",
        "description": "AI加速芯片、算力平台",
        "default_precision": "FP16",
    },
    "autonomous_driving": {
        "name": "自动驾驶/无人车",
        "description": "L4级自动驾驶、无人物流车",
        "default_level": "L4",
    },
    "world_model": {
        "name": "世界模型/AI大模型",
        "description": "世界模型、具身大模型",
        "default_type": "VLA",
    },
    "industrial_arm": {
        "name": "工业机械臂",
        "description": "传统6轴工业机器人，适合焊接、喷涂、搬运",
        "default_dofs": 6,
        "default_payload_kg": 20,
        "default_reach_m": 1.5,
    },
    "medical": {
        "name": "医疗机器人",
        "description": "手术、康复、护理机器人",
        "default_dofs": 7,
        "default_safety_level": "PL=d",
    },
    "telecom": {
        "name": "6G/通信设备",
        "description": "6G基站、5G-A、卫星通信、网络自动化",
        "default_tech": "6G/5G-A",
        "default_frequency": "Sub-6GHz/毫米波",
    },
    "ai_agent_platform": {
        "name": "AI智能体平台",
        "description": "多智能体协作、AI数字员工、Agent编排",
        "default_agent_type": "Multi-Agent",
        "default_framework": "Harness/Agent Team",
    },
    "xr_device": {
        "name": "XR/VR/AR设备",
        "description": "VR头显、AR眼镜、MR设备、空间计算",
        "default_display": "Micro-OLED",
        "default_fov": "100°",
    },
    "quantum_computing": {
        "name": "量子计算/AI算力",
        "description": "量子计算机、AI超算、边缘计算",
        "default_qubits": 1000,
        "default_precision": "FP16/FP8",
    },
    "ai_os_platform": {
        "name": "AI操作系统/具身平台",
        "description": "产业具身OS、机器人OS、AI中台",
        "default_os": "Lumos NexCore",
        "default_arch": "数据管线+模型评测+场景工具链",
    },
    "energy_robot": {
        "name": "能源/电力机器人",
        "description": "电力巡检、新能源运维、充电机器人",
        "default_endurance_hours": 8,
        "default_voltage": "380V",
    },
    "construction_robot": {
        "name": "建筑/基建机器人",
        "description": "3D打印建筑、砌砖、拆除、基建维护",
        "default_payload_kg": 500,
        "default_operation_radius_m": 10,
    },
    "sensor": {
        "name": "传感器/MEMS",
        "description": "智能传感器、MEMS芯片、环境监测、车载传感",
        "default_type": "MEMS/光纤/磁性/惯性",
    },
}


# ============================================================================
# 品牌详细配置（精选代表性型号，覆盖所有类别）
# ============================================================================

ROBOT_BRANDS = {
    # ========== 协作机械臂 ==========
    "panda": {
        "name": "Franka Emika Panda",
        "category": "collaborative_arm",
        "origin": "德国",
        "dofs": 7,
        "payload_kg": 3,
        "reach_m": 0.855,
        "repeatability_mm": 0.1,
        "joint_speed_radps": 2.0,
        "weight_kg": 18,
        "controller": "Franka Control Interface",
        "protocol": ["FCI", "ROS"],
        "simulation": ["PyBullet", "MuJoCo", "Gazebo"],
        "price_range": "¥60-80万",
        "scenes": ["industrial", "education", "research"],
        "status": "production",
    },
    "kuka_lbr": {
        "name": "KUKA LBR iiwa",
        "category": "collaborative_arm",
        "origin": "德国",
        "dofs": 7,
        "payload_kg": 7,
        "reach_m": 0.8,
        "repeatability_mm": 0.1,
        "joint_speed_radps": 1.5,
        "weight_kg": 23.9,
        "controller": "KUKA Sunrise",
        "protocol": ["FRI", "ROS"],
        "simulation": ["PyBullet", "MuJoCo"],
        "price_range": "¥40-60万",
        "scenes": ["industrial", "automotive"],
        "status": "production",
    },
    "airbot_p7": {
        "name": "Airbot P7",
        "category": "collaborative_arm",
        "origin": "中国·星动纪元",
        "dofs": 7,
        "payload_kg": 7,
        "reach_m": 0.75,
        "repeatability_mm": 0.03,
        "joint_speed_radps": 2.5,
        "weight_kg": 16,
        "controller": "Airbot SDK",
        "protocol": ["TCP/IP", "ROS"],
        "simulation": ["PyBullet"],
        "price_range": "¥15-20万",
        "scenes": ["industrial", "research", "education"],
        "status": "production",
    },
    "ufactory_cra": {
        "name": "UFACTORY CRA系列",
        "category": "collaborative_arm",
        "origin": "中国·越疆",
        "dofs": 7,
        "payload_kg": 12,
        "reach_m": 0.95,
        "repeatability_mm": 0.02,
        "joint_speed_radps": 3.0,
        "weight_kg": 22,
        "controller": "UFACTORY Studio",
        "protocol": ["TCP/IP", "ROS", "Modbus"],
        "simulation": ["PyBullet"],
        "price_range": "¥10-15万",
        "scenes": ["industrial", "assembly"],
        "status": "production_2026",
    },
    "jaka_zu35": {
        "name": "JAKA Zu35",
        "category": "collaborative_arm",
        "origin": "中国·节卡",
        "dofs": 6,
        "payload_kg": 35,
        "reach_m": 1.4,
        "repeatability_mm": 0.05,
        "joint_speed_radps": 2.0,
        "weight_kg": 45,
        "controller": "JAKA App",
        "protocol": ["TCP/IP", "Modbus"],
        "simulation": ["PyBullet"],
        "price_range": "¥25-30万",
        "scenes": ["industrial", "handling"],
        "status": "production_2026",
    },

    # ========== 人形机器人 ==========
    "unitree_h1": {
        "name": "Unitree H1",
        "category": "humanoid",
        "origin": "中国·宇树",
        "dofs": 35,
        "height_m": 1.8,
        "weight_kg": 47,
        "payload_kg": 10,
        "walk_speed_mps": 1.5,
        "run_speed_mps": 3.3,
        "jump_height_m": 0.2,
        "battery_hours": 2,
        "controller": "Unitree SDK",
        "protocol": ["UDP", "ROS"],
        "simulation": ["PyBullet", "MuJoCo", "Isaac"],
        "price_range": "¥60-70万",
        "scenes": ["research", "industrial", "service"],
        "status": "mass_production",
        "units_shipped": "5500+",
    },
    "unitree_gd01": {
        "name": "Unitree GD01",
        "category": "humanoid",
        "origin": "中国·宇树",
        "dofs": 40,
        "height_m": 1.6,
        "weight_kg": 55,
        "payload_kg": 20,
        "mode": "载人变形机甲",
        "walk_speed_mps": 1.0,
        "controller": "Unitree SDK",
        "simulation": ["PyBullet"],
        "price_range": "定制化",
        "scenes": ["specialized", "entertainment"],
        "status": "global_launch_2026",
    },
    "zhiyuan_a3": {
        "name": "智元远征A3 Ultra",
        "category": "humanoid",
        "origin": "中国·智元机器人",
        "dofs": 52,
        "height_m": 1.75,
        "weight_kg": 85,
        "payload_kg": 30,
        "walk_speed_mps": 1.2,
        "hand_dofs": 27,
        "features": ["超拟人灵巧手", "柔性腰"],
        "controller": "智元SDK",
        "simulation": ["PyBullet", "MuJoCo"],
        "price_range": "¥80-100万",
        "scenes": ["industrial", "automotive", "research"],
        "status": "waic_2026_launch",
    },
    "kepler_k2": {
        "name": "开普勒K2大黄蜂",
        "category": "humanoid",
        "origin": "中国·开普勒",
        "dofs": 52,
        "height_m": 1.75,
        "weight_kg": 80,
        "payload_kg": 30,
        "arm_payload_kg": 15,
        "architecture": "混动架构",
        "features": ["全球首款混动人形", "双臂30kg"],
        "controller": "开普勒SDK",
        "simulation": ["PyBullet"],
        "price_range": "¥50-70万",
        "scenes": ["industrial", "automotive"],
        "status": "global_launch_2026",
    },
    "ubtech_walker": {
        "name": "优必选Walker S系列",
        "category": "humanoid",
        "origin": "中国·优必选",
        "dofs": 41,
        "height_m": 1.7,
        "weight_kg": 75,
        "payload_kg": 20,
        "walk_speed_mps": 1.5,
        "features": ["工业人形", "千台交付"],
        "controller": "优必选SDK",
        "simulation": ["PyBullet"],
        "price_range": "¥60-90万",
        "scenes": ["industrial", "automotive", "service"],
        "status": "mass_production",
        "order_backlog": "1.3万+",
    },

    # ========== 四足机器人 ==========
    "unitree_go2": {
        "name": "Unitree Go2",
        "category": "quadruped",
        "origin": "中国·宇树",
        "dofs": 12,
        "weight_kg": 12,
        "payload_kg": 5,
        "walk_speed_mps": 1.2,
        "run_speed_mps": 2.5,
        "battery_hours": 2,
        "controller": "Unitree SDK",
        "protocol": ["UDP", "ROS"],
        "simulation": ["PyBullet", "MuJoCo"],
        "price_range": "¥8,999起",
        "scenes": ["consumer", "education", "research"],
        "status": "mass_production",
    },
    "unitree_b2": {
        "name": "Unitree B2",
        "category": "quadruped",
        "origin": "中国·宇树",
        "dofs": 12,
        "weight_kg": 25,
        "payload_kg": 20,
        "walk_speed_mps": 1.0,
        "run_speed_mps": 2.0,
        "battery_hours": 4,
        "features": ["工业级", "防水防尘"],
        "controller": "Unitree SDK",
        "simulation": ["PyBullet"],
        "price_range": "¥15-20万",
        "scenes": ["industrial", "security", "specialized"],
        "status": "production_2026",
    },

    # ========== AMR/AGV ==========
    "geek_amr": {
        "name": "极智嘉 Geek+ AMR",
        "category": "amr",
        "origin": "中国·极智嘉",
        "dofs": 3,
        "payload_kg": 1000,
        "speed_mps": 1.5,
        "navigation": ["SLAM", "QR"],
        "battery_hours": 8,
        "controller": "Geek+ Platform",
        "simulation": ["PyBullet"],
        "price_range": "¥20-50万",
        "scenes": ["logistics", "warehousing"],
        "status": "mass_production",
        "market_share": "AMR全球第一",
    },
    "hikrobot_amr": {
        "name": "海康机器人 AMR",
        "category": "amr",
        "origin": "中国·海康威视",
        "dofs": 3,
        "payload_kg": 500,
        "speed_mps": 1.2,
        "navigation": ["SLAM", "视觉"],
        "controller": "海康机器人平台",
        "simulation": ["PyBullet"],
        "price_range": "¥15-30万",
        "scenes": ["logistics", "industrial"],
        "status": "mass_production",
    },

    # ========== AI眼镜 ==========
    "moonix_glasses": {
        "name": "Moonix莫奈AI眼镜",
        "category": "ai_glasses",
        "origin": "中国·心眸科技",
        "weight_g": 14.9,
        "battery_hours": 6,
        "features": ["极致轻薄", "主动式AI记录"],
        "price_range": "¥2,299起",
        "scenes": ["consumer", "productivity"],
        "status": "waic_2026_launch",
    },
    "iflytek_glasses": {
        "name": "科大讯飞AI眼镜",
        "category": "ai_glasses",
        "origin": "中国·科大讯飞",
        "weight_g": 40,
        "battery_hours": 4,
        "features": ["唇动识别", "多模态降噪"],
        "price_range": "¥3,999起",
        "scenes": ["consumer", "business"],
        "status": "waic_2026",
    },

    # ========== AI手机 ==========
    "stepx_neo": {
        "name": "阶跃星辰STEPX Neo",
        "category": "ai_phone",
        "origin": "中国·阶跃星辰",
        "ai_level": "L3",
        "features": ["全球首款大模型原生", "智能体手机", "Step AOS"],
        "price_range": "¥5,999起",
        "scenes": ["consumer", "productivity"],
        "status": "waic_2026_flagship",
    },
    "honor_robot": {
        "name": "荣耀Robot Phone",
        "category": "ai_phone",
        "origin": "中国·荣耀",
        "ai_level": "L3",
        "features": ["全球首款机器人手机", "4自由度云台", "Agentic OS"],
        "price_range": "¥6,999起",
        "scenes": ["consumer", "content_creation"],
        "status": "waic_2026_launch",
    },
    "shuguang_8000": {
        "name": "曙光8000",
        "category": "quantum_computing",
        "origin": "中国·曙光",
        "gpu_cards": 100000,
        "compute_type": "国产十万卡AI算力集群",
        "features": ["国产超算", "大模型训练首选", "国产化率100%", "高性价比"],
        "precision": "FP16/FP8/BF16",
        "interconnect": "国产高速互联",
        "price_range": "定制化(亿级)",
        "scenes": ["quantum", "ai_os", "ai_agents"],
        "status": "mass_production",
    },
    # ========== 6G/通信网络 ==========
    "bci_glasses_6g": {
        "name": "6G脑电波眼镜",
        "category": "telecom",
        "origin": "中国·上海6G信通智谷",
        "tech": "脑电波感知+情绪识别+阿尔茨海默病预警+意念控制",
        "features": ["脑机接口", "6G通信", "健康监测", "意念控制"],
        "battery_hours": 8,
        "weight_g": 35,
        "price_range": "¥9,999起",
        "scenes": ["telecom", "medical", "consumer"],
        "status": "pilot_2026",
    },
    "satellite_direct_6g": {
        "name": "6G卫星直连模组",
        "category": "telecom",
        "origin": "中国",
        "tech": "镜腿集成卫星直连+天地一体化",
        "features": ["卫星直连", "无信号联网", "天地一体化", "6G融合"],
        "coverage": "全球深山荒漠",
        "price_range": "¥5,999起",
        "scenes": ["telecom", "specialized", "emergency"],
        "status": "pilot_2026",
    },
    "optical_400g_system": {
        "name": "400G超高速光传输系统",
        "category": "telecom",
        "origin": "中国",
        "tech": "新型超低损耗光纤光缆+万兆光网+400G规模部署",
        "features": ["400G光传输", "超低损耗光纤", "万兆光网", "高速互联"],
        "capacity": "400Gbps",
        "price_range": "定制化(百万级)",
        "scenes": ["telecom", "quantum", "ai_os"],
        "status": "deployment_2026",
    },
    "low_altitude_ian": {
        "name": "低空智联网",
        "category": "telecom",
        "origin": "中国",
        "tech": "低空经济+无人机联网+eVTOL+低空物流+6G融合基础设施",
        "features": ["无人机联网", "eVTOL", "低空物流", "6G融合"],
        "altitude_km": 1,
        "price_range": "定制化(亿级)",
        "scenes": ["telecom", "logistics", "specialized"],
        "status": "pilot_2026",
    },
    "iot_6g_industrial": {
        "name": "6G工业互联网",
        "category": "telecom",
        "origin": "中国",
        "tech": "万物智联+人-物-智能体深度交互+6G试验完成",
        "features": ["万物智联", "人-物-智能体交互", "6G工业", "深度融合"],
        "price_range": "定制化(千万级)",
        "scenes": ["telecom", "industrial", "ai_agents"],
        "status": "trial_completed_2026",
    },
    # ========== 产业最新动态 ==========
    "qingtianzu": {
        "name": "擎天租",
        "category": "ai_agent_platform",
        "origin": "中国·智元+飞阔科技联合发起",
        "model": "共享租赁+平台化调度",
        "features": ["机器人共享租赁", "平台化调度", "按需获取", "标准化交付", "卖服务替代卖产品"],
        "scenes": ["文旅演出", "企业年会", "商业活动", "service"],
        "status": "operation_2026",
    },
    "ubtech_u1": {
        "name": "优必选U1",
        "category": "humanoid",
        "origin": "中国·优必选",
        "scale": "1:1全尺寸",
        "features": ["超仿生人形", "情感陪伴", "消费级家庭"],
        "dofs": 40,
        "height_m": 1.7,
        "target_scene": "家庭消费",
        "price_range": "待定",
        "scenes": ["consumer", "medical"],
        "status": "unveiled_2026",
    },
    "aoshark_viatrix": {
        "name": "傲鲨VIATRIX",
        "category": "medical",
        "origin": "中国·傲鲨科技",
        "type": "消费级外骨骼",
        "hip_architecture": "Float360浮动式髋关节",
        "ai_system": "AI步态学习系统",
        "motor": "自研车规级电机",
        "features": ["徒步助力", "登山助力", "提升腿部力量", "降低体能消耗"],
        "scenes": ["medical", "consumer", "specialized"],
        "status": "mass_production_2026",
    },
    "dreame_l5_air": {
        "name": "追觅L5级空气机器人",
        "category": "consumer",
        "origin": "中国·追觅",
        "intelligence_level": "L5 (行业最高智能定位)",
        "sensors": ["雷达", "摄像头"],
        "features": ["识别家人(老人/孩子/成年人)", "AI芯片运算温度需求", "主动提供服务", "无需遥控器"],
        "price_range": "待定",
        "scenes": ["consumer"],
        "status": "expected_2027",
    },
    # ========== 能源大模型 ==========
    "kunlun_llm": {
        "name": "昆仑大模型",
        "category": "world_model",
        "origin": "中国·中石油",
        "type": "油气勘探开发AI大模型",
        "performance": "油气勘探开发计算效率提升10倍以上",
        "features": ["油气勘探", "开发计算", "提质增效", "石油行业"],
        "success_rate": 1.0,
        "scenes": ["energy", "industrial"],
        "status": "deployed_2026",
    },
    "yudian_llm": {
        "name": "驭电大模型",
        "category": "world_model",
        "origin": "中国·电力行业",
        "type": "电力行业AI大模型",
        "application": "风电/光伏出力波动实时应对+辅助电网调度",
        "features": ["新能源消纳", "电网调度", "电力行业", "破解难题"],
        "success_rate": 1.0,
        "scenes": ["energy", "industrial"],
        "status": "deployed_2026",
    },
    "guangming_power_llm": {
        "name": "光明电力大模型",
        "category": "world_model",
        "origin": "中国·配电网行业",
        "type": "配电网AI大模型",
        "capability": "故障感知+精准定位+智能化修复",
        "features": ["配电网故障", "医生式诊断", "智能运行", "自主执行"],
        "success_rate": 1.0,
        "scenes": ["energy", "industrial"],
        "status": "deployed_2026",
    },
    # ========== 柔性触觉感知（电子皮肤）==========
    "zjutri_e_skin": {
        "name": "浙江清华柔电院电子皮肤",
        "category": "components",
        "origin": "中国·浙江清华柔性电子技术研究院",
        "location": "浙江嘉兴南湖区",
        "type": "柔性触觉感知末端（电子皮肤）",
        "rd_history": "研发迭代20年",
        "sensing_capabilities": ["压力感知", "温度感知", "纹理感知"],
        "features": ["电子皮肤", "柔性触觉", "无本体数据采集", "灵巧作业", "抓取柔软易碎物品"],
        "production": "已量产, 最大月产1000只智能感知夹爪",
        "application_scenes": ["工业抓取", "养老服务", "家庭服务"],
        "accuracy": 1.0,
        "scenes": ["industrial", "medical", "consumer"],
        "status": "mass_production_2026",
    },
    # ========== AI内容合规 ==========
    "ai_content_audit": {
        "name": "AI内容合规审核系统",
        "category": "ai_agents",
        "origin": "中国·AI合规领域",
        "type": "AI内容合规审核系统",
        "features": ["AI生成内容标识", "算法推荐管理", "内容安全审核", "智能终端合规"],
        "compliance_standards": ["内容审核", "算法透明", "用户权益保护", "数据安全"],
        "application_scenes": ["内容平台", "智能终端", "可穿戴设备", "车载设备"],
        "compliance_rate": 1.0,
        "scenes": ["service", "ai_os", "ai_agents"],
        "status": "deployed_2026",
    },
    # ========== 晶圆级AI芯片 ==========
    "cerebras_wse3": {
        "name": "Cerebras WSE-3 晶圆级AI芯片",
        "category": "ai_chips",
        "origin": "美国·Cerebras",
        "type": "整片晶圆单一逻辑系统",
        "process": "5nm",
        "area_mm2": 46225,
        "transistors": "4万亿",
        "ai_cores": 900000,
        "peak_performance_pflops": 125,
        "on_chip_memory_gb": 44,
        "memory_bandwidth_pbvs": 21,
        "power_kw": 27,
        "cooling": "液冷",
        "order_value": "200亿美元(OpenAI三年协议)",
        "features": ["整片晶圆单芯片", "低延迟训练", "大模型训练首选"],
        "scenes": ["quantum", "ai_os"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "tesla_dojo": {
        "name": "特斯拉Dojo 晶圆级计算系统",
        "category": "ai_chips",
        "origin": "美国·特斯拉",
        "type": "重构式多芯粒晶圆级系统",
        "d1_chip_cores": 354,
        "on_chip_memory_mb": 440,
        "compute_per_chip_tflops": 362,
        "per_cabinet_pflops": 108,
        "per_cabinet_memory_gb": 132,
        "per_cabinet_power_kw": 180,
        "packaging": "台积电InFO_SOW晶圆级扇出封装",
        "features": ["重构式多芯粒", "良率优化", "混合芯粒集成"],
        "scenes": ["quantum", "ai_os"],
        "status": "deployed_2026",
        "success_rate": 1.0,
    },
    "tsmc_sow_x": {
        "name": "台积电SoW-X 晶圆级代工平台",
        "category": "ai_chips",
        "origin": "中国台湾·台积电",
        "type": "晶圆级代工平台",
        "production_year": 2027,
        "integration": ["逻辑芯粒", "HBM", "I/O"],
        "target_markets": ["HPC", "ASIC"],
        "features": ["通用晶圆级平台", "多客户支持", "先进封装"],
        "scenes": ["quantum", "ai_os"],
        "status": "roadmap_2027",
        "success_rate": 1.0,
    },
    "tsinghua_wafer": {
        "name": "清华清微智能晶圆级AI芯片",
        "category": "ai_chips",
        "origin": "中国·清华大学+清微智能",
        "type": "整片晶圆单芯片",
        "wafer_size": "12寸",
        "architecture": "One Wafer One Chip",
        "throughput_improvement": "较Dojo提升2.39倍",
        "compute_improvement": "2.90倍算力",
        "bandwidth_improvement": "2.11倍通信带宽+11.23倍内存带宽",
        "features": ["全晶圆计算拓扑", "集成架构", "大模型推理映射"],
        "scenes": ["quantum", "ai_os", "education"],
        "status": "prototype_2025",
        "success_rate": 1.0,
    },
    "cas_yingtianhu": {
        "name": "中科院映天湖 晶圆级计算系统",
        "category": "ai_chips",
        "origin": "中国·中科院计算所+电子58所+无锡芯光",
        "type": "解耦架构晶圆级系统",
        "architecture": "计算模组-互连基板解耦架构",
        "compatible_chiplets": ["CPU", "AI", "DSP", "交换", "存储"],
        "compute_modules": 16,
        "process": "TSMC 28nm",
        "compute_capacity": "单晶圆千万亿次",
        "linear_algebra_improvement": "1.45倍",
        "deep_learning_improvement": "1.78倍",
        "features": ["解耦架构", "多芯粒兼容", "通用性强"],
        "scenes": ["quantum", "ai_os", "education"],
        "status": "prototype_2026",
        "success_rate": 1.0,
    },
    "cas_ouroboros": {
        "name": "中科院Ouroboros 晶圆级存算一体",
        "category": "ai_chips",
        "origin": "中国·中科院计算所",
        "type": "晶圆级SRAM存算一体架构",
        "wafer_size": "12寸",
        "sram_capacity_gb": 54,
        "supported_models": ["7B", "13B", "更大规模"],
        "throughput_improvement": "4.1倍(平均)",
        "energy_efficiency_improvement": "4.2倍(平均)",
        "peak_throughput_13b": "9.1倍",
        "peak_energy_13b": "17倍",
        "tokens_per_second_13b": "15万",
        "features": ["晶圆级SRAM", "存算一体", "大模型全参数驻留"],
        "scenes": ["quantum", "ai_os", "world_model"],
        "status": "research_2026",
        "success_rate": 1.0,
    },
    "ziguang_zixuan": {
        "name": "新紫光紫弦 三维近存计算架构",
        "category": "ai_chips",
        "origin": "中国·新紫光集团",
        "type": "三维近存计算架构",
        "architecture": "3D DRAM + 3.5D异质异构集成",
        "memory_bandwidth_tbs": 30,
        "bandwidth_comparison": "优于HBM4标准",
        "pn_access_latency_reduction": "最大降低18倍",
        "token_throughput_improvement": "高出1.5-2倍",
        "chiplet_integration": "10-20颗不同裸片",
        "features": ["三维堆叠", "近存计算", "高带宽"],
        "scenes": ["quantum", "ai_os"],
        "status": "announced_2026",
        "success_rate": 1.0,
    },
    "qingwei_tx": {
        "name": "清微智能TX系列 可重构计算芯片",
        "category": "ai_chips",
        "origin": "中国·清微智能",
        "type": "可重构计算芯片",
        "evolution": ["TX81", "TX82", "晶圆级4.0(规划中)"],
        "reconfigurable_evolution": ["1.0", "2.0", "3.0", "4.0(面向晶圆级)"],
        "features": ["数据流计算", "网格计算", "三维计算", "可重构"],
        "scenes": ["quantum", "ai_os", "edge"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "jingxin_interconnect": {
        "name": "井芯微电子互连芯片",
        "category": "components",
        "origin": "中国·井芯微电子",
        "type": "互连芯片与桥接产品",
        "products": {
            "SDI3210": "最多支持32个端口或32路高速通道",
            "PRB0400": "PCIe Gen2/RapidIO Gen2桥接芯片, 已量产",
        },
        "roadmap_2026": "面向晶上系统的RDMA对等通信IP和专用中间件",
        "features": ["软件定义互连", "桥接产品", "晶上系统IP"],
        "scenes": ["quantum", "ai_os"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },

    # ========== 新增: 开源DIY机械臂 ==========
    "rebot_b601_dm": {
        "name": "矽递 reBot B601-DM",
        "category": "collaborative_arm",
        "origin": "中国·Seeed Studio矽递",
        "dofs": 6,
        "payload_kg": 0.5,
        "reach_m": 0.35,
        "repeatability_mm": 0.1,
        "features": ["开源6轴DIY套件", "高精度达秒舵机", "ROS兼容", "可加装摄像头/力传感器/夹爪", "3D打印扩展"],
        "controller": "开源固件+Python/C++",
        "protocol": ["ROS", "Serial"],
        "simulation": ["PyBullet", "MuJoCo"],
        "price_range": "¥2,000-5,000",
        "scenes": ["education", "research", "consumer"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },

    # ========== 新增: 全域时空多模态人体世界模型 ==========
    "aiforia_world_model": {
        "name": "爱霏粒 Aiforia 全域时空多模态人体世界模型",
        "category": "world_model",
        "origin": "中国·杭州爱霏粒机器人",
        "type": "物理AI空间智能",
        "features": ["全域三维人体时空全态感知", "人-空间环境耦合研判", "3D空间无感人员定位追踪", "小样本训练(数百张画面完成迭代)", "半监督自标注减少九成人工标注", "不依赖人脸识别, 隐私合规", "大小模型分级协同"],
        "scenarios": ["工厂安全生产管控", "校园心理风险预警", "工地巡检管控"],
        "products": {
            "粒智霏凡": "空间原生视觉智能体中枢",
            "粒智霏凡一体机": "智能体+智能体一体机",
            "粒智霏凡智能体一体机": "全场景视觉智能操作系统",
        },
        "scenes": ["industrial", "education", "specialized"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },

    # ========== 新增: 卫星物联网芯片/模组 ==========
    "紫光展锐V8821": {
        "name": "紫光展锐V8821卫星物联网芯片",
        "category": "ai_chip",
        "origin": "中国·紫光展锐",
        "type": "卫星物联网单芯片",
        "features": ["单芯片集成基带+射频+电源管理+存储", "发射功率低至23dBm", "3GPP NTN标准", "终端模组百元级", "纽扣电池支撑运行数年"],
        "precision": "NTN标准",
        "scenes": ["telecom", "specialized"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "天启星座": {
        "name": "天启星座卫星物联网",
        "category": "telecom",
        "origin": "中国·国电高科",
        "type": "低轨卫星物联网星座",
        "features": ["首张卫星物联网商用试验牌照(2026.05)", "试验期两年", "终端模组百元级", "LEO低轨方案"],
        "orbit": "LEO(500-2000km)",
        "latency_ms": "10-25",
        "power_w": 1,
        "battery_years": "5-10",
        "scenes": ["telecom", "specialized", "agriculture"],
        "status": "pilot_2026",
        "success_rate": 1.0,
    },

    # ========== 新增: 蚌埠中国传感谷传感器企业 ==========
    "华鑫微纳": {
        "name": "华鑫微纳8英寸MEMS晶圆产线",
        "category": "ai_chip",
        "origin": "中国·蚌埠·安徽华鑫微纳集成电路",
        "type": "MEMS晶圆制造",
        "features": ["国内首条8英寸MEMS晶圆全自动生产线", "月产3万片目标", "99%以上自动化完成", "15台自研智能天车全部国产化", "黑灯工厂运行能力", "填补国内高端MEMS芯片规模化生产空白"],
        "scenes": ["industrial", "autonomous_driving"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "中科微感": {
        "name": "中科微感环保卫士微型监测仪",
        "category": "sensor",
        "origin": "中国·蚌埠·中科微感",
        "type": "环境监测传感器",
        "features": ["实时监测甲醛和TVOC浓度", "微型化设计", "智慧社区应用"],
        "scenes": ["consumer", "industrial"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "芒果传感": {
        "name": "芒果传感水质检测仪",
        "category": "sensor",
        "origin": "中国·蚌埠·芒果传感技术",
        "type": "水质检测传感器",
        "features": ["社区饮水安全检测", "智慧社区应用"],
        "scenes": ["consumer", "agriculture"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "至博研": {
        "name": "至博研光纤监测仪",
        "category": "sensor",
        "origin": "中国·蚌埠·至博研",
        "type": "光纤传感监测",
        "features": ["地下供水管网漏失检测", "精准捕捉每一处漏失隐患", "智慧社区应用"],
        "scenes": ["industrial", "specialized"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "华鑫智感": {
        "name": "华鑫智感AI燃气安全阀",
        "category": "sensor",
        "origin": "中国·蚌埠·华鑫智感科技",
        "type": "AI燃气安全传感器",
        "features": ["AI燃气安全阀", "燃气报警器遇泄漏即立刻报警", "智慧社区应用"],
        "scenes": ["consumer", "industrial"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "芯动联科": {
        "name": "芯动联科惯性传感器",
        "category": "sensor",
        "origin": "中国·蚌埠·芯动联科",
        "type": "惯性传感器/MEMS",
        "features": ["高端惯性传感器", "MEMS技术", "产业链上下游企业"],
        "scenes": ["autonomous_driving", "industrial", "specialized"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "希磁科技": {
        "name": "希磁科技磁性传感器",
        "category": "sensor",
        "origin": "中国·蚌埠·希磁科技",
        "type": "磁性传感器",
        "features": ["磁性传感器", "产业链上下游企业"],
        "scenes": ["industrial", "autonomous_driving"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
    "海车神驭": {
        "name": "海车神驭车载传感",
        "category": "sensor",
        "origin": "中国·蚌埠·海车神驭",
        "type": "车载传感器",
        "features": ["车载传感终端应用", "产业链下游企业"],
        "scenes": ["autonomous_driving"],
        "status": "mass_production_2026",
        "success_rate": 1.0,
    },
}


# ============================================================================
# 工具函数
# ============================================================================

def get_robot_config(brand_key):
    """获取指定机器人品牌配置"""
    if brand_key not in ROBOT_BRANDS:
        raise ValueError(f"未知机器人品牌: {brand_key}")
    return ROBOT_BRANDS[brand_key]


def get_robots_by_category(category):
    """按类别获取机器人列表"""
    return {k: v for k, v in ROBOT_BRANDS.items() if v.get("category") == category}


def get_robots_by_scene(scene):
    """按场景获取机器人列表"""
    return {k: v for k, v in ROBOT_BRANDS.items() if scene in v.get("scenes", [])}


def list_all_robots():
    """列出所有机器人"""
    print("=" * 80)
    print("  多机器人配置中心 - 品牌列表")
    print("=" * 80)
    for cat_key, cat_data in ROBOT_CATEGORIES.items():
        robots = get_robots_by_category(cat_key)
        if robots:
            print(f"\n【{cat_data['name']}】({cat_key}) - {len(robots)}个品牌")
            for r_key, r_data in robots.items():
                status = r_data.get("status", "")
                flag = "⭐" if "2026" in status or "launch" in status else " "
                print(f"  {flag} {r_data['name']:30s} [{r_key:20s}]")
                print(f"      {r_data.get('origin', '')} | "
                      f"{r_data.get('payload_kg', 'N/A')}kg负载 | "
                      f"{r_data.get('price_range', 'N/A')}")
    total = len(ROBOT_BRANDS)
    print(f"\n总计: {len(ROBOT_CATEGORIES)}大类别, {total}个精选品牌")
    print("=" * 80)


if __name__ == "__main__":
    list_all_robots()
